create table public.notes (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.notes enable row level security;

create policy "Allow public read access to notes"
on public.notes
for select
using (true);
